### ISSUE TITLE
API Service bugs and issues.

### ISSUE THREAD

**Issue by Darrrren** [Anteris-Dev/autotask-client#12]
I thought it might be a good idea for us all to share information regarding defects or issues in the API service itself at the Datto end, as it's only just been launched. This should help us all diagnose any unexpected behaviour in our own projects whilst using the new REST API.  Please share any API endpoint / method / model issues you are aware of, including any documentation issues.

**Comment by Darrrren** [comment]
I'm having issues with the following endpoints:
CompanyLocations
Contacts 
They're both returning a 404, Datto have raised a ticket

**Comment by aidan-casey** [comment]
Thanks @Darrrren!

> I'm having issues with the following endpoints:
> CompanyLocations
> Contacts
> They're both returning a 404, Datto have raised a ticket

I'm curious about this. What is the expected result of your requests? A root GET request against /Contacts or /CompanyLocations should probably return a 405 error with the message:

```json
{"Message":"The requested resource does not support http method 'GET'."}
```

Though you are correct, right now it returns a 404.

**Comment by Darrrren** [comment]
Yeah I was expecting a 405 from the root as well but, alas, the URL of the endpoint itself isn't working.  I haven't come across any others but I'm sure there will be more as we've only been working with Companies and Tickets so far in our own project.

**Comment by aidan-casey** [comment]
Thankfully that is not a breaking change surrounding CRUD actions against those endpoints. 👍

**Comment by Darrrren** [comment]
Datto have acknowledged those 2 endpoints should return a 405 as mentioned above by @aidan-casey, not a 404 as is currently the case. They're looking to resolve it but no date given. No biggy.

**Comment by aidan-casey** [comment]
In doing some testing, we have found the following problems with the Autotask API. Autotask has been notified.

- ContractNotes contractID is listed as string but is actually integer (long?)
- Contracts include userDefinedFields in response, but shouldn’t.
- InvoiceTemplates paymentTerms field is supposed to be required but returns null.
- OpportunityAttachments return fields `id` and `data` both of which are not specified in entityInformation.
- Opportunities include userDefinedFields in response, but shouldn’t.
- Products include userDefinedFields in response, but shouldn’t.
- ProjectAttachments return fields `id` and `data` both of which are not specified in entityInformation.
- PurchaseOrderItemReceiving field quantityNowReceiving is supposed to be required but returns null.
- SalesOrders include userDefinedFields in response, but shouldn’t.
- Projects include userDefinedFields in response, but shouldn’t.
- TaskAttachments return fields `id` and `data` both of which are not specified in entityInformation.
- TicketAttachments return fields `id` and `data` both of which are not specified in entityInformation.
- Tasks include userDefinedFields in response, but shouldn’t.
- Tickets include userDefinedFields in response, but shouldn’t.

**Comment by Darrrren** [comment]
Do any of these issues affect basic CRUD functionality in the package?

**Comment by aidan-casey** [comment]
> Primarily they are impacting the query (or read) actions against the API. This package expects entities to be returned as defined by /entityInformation and /entityInformation/fields (and they should be) but Autotask is inconsistent with the response. I have some quick fixes that will be ready for release soon. These will resolve those issues the best we can without Autotask fixing their end. They have been alerted to the issues. [#15]

We are making these top priority right now and I have been in active communication with Autotask.

**Comment by aidan-casey** [comment]
Latest update addresses all of the above. 😎

**Comment by aidan-casey** [comment]
@Darrrren - I am going to close this issue in favor of notifying users through the Discord channel now listed in the README. My primary reason for this is to keep the issues limited to problems with this package so we can quickly pick them off.

**Comment by Darrrren** [comment]
Roger that
