### ISSUE TITLE
Dependencies documentation

### ISSUE THREAD

**Issue by Darrrren** [Anteris-Dev/autotask-client#13]
It might be worth mentioning in the README.md that PHP 7.4 as a prerequisite dependency at this early stage like you've done in the data-transfer-object github readme file. 

> spatie/data-transfer-object 2.5.0 requires php ^7.4 -> your PHP version (7.3.1) does not satisfy that requirement.

That's a show stopper for me for today unfortunately, I'll have to build something new next week to be able to get this up and running as I'm still on 7.3.1 [blushing slightly] as you can see :-)

**Comment by aidan-casey** [comment]
Sorry about that! Thanks @Darrrren for the feedback though. You are correct, we should have noted that in the README. I will look to have that updated in the next couple of days, or a pull request is always welcome.

Definitely recommend you get 7.4 installed as able, it brings a lot to the table. Also worth mentioning that as PHP 8 is released we will probably look to get this package upgraded to that version as well. It brings several breaking changes.

**Comment by Darrrren** [comment]
Morning Aidan, I'm sharing my "vanilla install" journey as I'm having niggles with dependencies which everyone will hit doing a clean Laravel install then immediately trying to install the library. Might be another dependency 1 liner coming up in the readme.md when I figure out the easiest route through it. Here's the steps to recreate:

I now have PHP 7.4.8 installed on my local WAMP server and a fresh instance of Laravel downloaded using Composer with the following command:

`composer create-project --prefer-dist laravel/laravel project`

Composer built the usual composer.json for me and included the following libraries and versions in the require section:

```
"require": { 
      "php": "^7.2.5",                                                                                                                                                          
      "fideloper/proxy": "^4.2",                                                                                                                                                
      "fruitcake/laravel-cors": "^2.0",                                                                                                                                         
      "guzzlehttp/guzzle": "^6.3",                                                                                                                                              
      "laravel/framework": "^7.24",                                                                                                                                             
      "laravel/tinker": "^2.0"
},
```

After the Laravel installation had finished, I ran the following command to install the library:

`composer require anteris-dev/autotask-client`

It fails and we can see that there's a dependency issue around guzzle  

>Problem 1
>- Installation request for anteris-dev/autotask-client ^0.2.0 -> satisfiable by anteris-dev/autotask-client[v0.2.0].
>- Conclusion: remove guzzlehttp/guzzle 6.5.5
>- Conclusion: don't install guzzlehttp/guzzle 6.5.5
>- anteris-dev/autotask-client v0.2.0 requires guzzlehttp/guzzle 7.* -> satisfiable by guzzlehttp/guzzle[7.0.x-dev, 7.1.x-dev].
>- Can only install one of: guzzlehttp/guzzle[7.0.x-dev, 6.5.5].
>- Can only install one of: guzzlehttp/guzzle[7.1.x-dev, 6.5.5].
>- Installation request for guzzlehttp/guzzle (locked at 6.5.5, required as ^6.3) -> satisfiable by guzzlehttp/guzzle[6.5.5].

My first thought is just to bump up the guzzle version number in the require section from ^6.3 to ^7.0 to resolve it but I'm slightly nervous of this as guzzle is a core library of Laravel and the latest Laravel requires ^6.3.

I'll do some reading and report back shortly.

**Comment by Darrrren** [comment]
Resolved... So after reading the GUZZLE repository changelog found here: [https://github.com/guzzle/guzzle/blob/master/CHANGELOG.md#700-beta1---2019-12-30](url)  it states that:

>95% of Guzzle users will be able to upgrade without modification

Therefore, based on the fact that Laravel is very popular framework and would certainly be represented in the 95% mentioned above, I changed my guzzle dependency up to 7.0 and was able to install everything, including the library no problem.    

So, for the benefit of the Laravel reader, here's how I installed this library into a fresh instance of Laravel.

1. Make sure you are running PHP 7.4 or higher, this is a perquisite of this library and you wont be able to install it without it.
2. Install an instance of Laravel using the following command:
    `composer create-project --prefer-dist laravel/laravel project` assuming `project` will be the name of the directory and project name.
3. When the installation has finished, edit the composer.json. In the `"require"` section, change the `"guzzlehttp/guzzle": "^6.3",` to `"guzzlehttp/guzzle": "^7.0",`
4. Upgrade the guzzle library with the following command:
    `composer update`
5. Finally, install this library with the following command: 
    `composer require anteris-dev/autotask-client`

To conclude Aidan, I would recommend also adding Guzzle 7.0 as a prerequisite library together with PHP 7.4 in the README.md

**Comment by aidan-casey** [comment]
@Darrrren Thanks for the feedback and documentation here! It is very helpful to me and any users that may plan to use this package. 

We definitely want this package to play nice with Laravel, we have even contemplated writing a package to tie it into the Laravel infrastructure. Keeping this in mind, I would be half tempted to actually bump that dependency down, but because of the close arrival of Laravel 8, I may leave this as is unless it is a major issue for anyone. The Laravel framework currently uses version 6.3 of Guzzle, but updates this to 7.0.1 in Laravel 8 which will be released on September eighth.

I am going to be making some updates to this package over the weekend and will include your notes in the README.

Shoot me a message if you need anything as you play with it. I hope you find the package useful!

**Comment by Darrrren** [comment]
Thanks Aidan, check your Facebook messenger ;-)
Are you considering making Laravel 8 a prerequisite to this package then?
It's going to take me a while to learn how everything works obviously, you know what it's like trying to figure out someone else code ;-)  I need to work out a few "best practices" as well but yes I'm up and running and certainly interacting with the API just fine in a Hello World basic setup so far. No wobblies to report as yet.

**Comment by Darrrren** [comment]
>I would be half tempted to actually bump that dependency down, but because of the close arrival of Laravel 8, I may leave this as is unless it is a major issue for anyone. 

Yeah I'm struggling today because of Guzzle 7. None of the other packages I need to use will support it, they all need ^6.3 so I've come to a complete stop now unfortunately.  Time for coffee and a think!  Any ideas at your end?

**Comment by aidan-casey** [comment]
@Darrrren - Received! :-)

I am not, I would like this package to be usable outside the Laravel realm as well. If anything we would create a wrapper for this package that ties into Laravel (e.g. makes use of Laravel configurations, installs a provider for the client, etc.). An example of this would be [this](https://github.com/GrahamCampbell/Laravel-GitLab) package which is simply a wrapper for another client.

Fair enough! Let me know if you have questions I can help you out with.

That's no good. I think I can bump down that requirement without too much damage and I do not see any reason not to. While you get that coffee I will work on an update to the requirements.

**Comment by aidan-casey** [comment]
@Darrrren Please try updating your version of this package to v0.2.1.

**Comment by Darrrren** [comment]
Fantastic @aidan-casey, will do, I'll try it now - thank you :-)

**Comment by Darrrren** [comment]
@aidan-casey you're legend! That works perfectly, consider yourself 1 beer in credit thanks ;-)

I'm back up and running again, I'll no doubt have a question or two over the next few of days, I'll reach out and drop you a message if that's ok?

**Comment by aidan-casey** [comment]
@Darrrren awesome! Glad it worked out for you. :-)

Absolutely! Look forward to hearing from you.
