### ISSUE TITLE
Documentation Website

### ISSUE THREAD

**Issue by aidan-casey** [Anteris-Dev/autotask-client#16]
We need to tackle putting together a documentation website. In the latest versions of this package we have decided to remove the phpdoc generated documentation from the actual repository. This is because we do not think it is necessary to add that sort of file storage to this package and also clutter up our commits with the constantly changing documentation.

This is not to say that a separate repo for documentation would be a bad thing. This is something we need to tackle.

**Comment by aidan-casey** [comment]
We are going to need two forms of documentation. Class docs (e.g. phpdoc) and usage docs (similar to what we have in the README). Looking at Blade UI Kit I think we can do something snazzy with the latter.

**Comment by JoshNW** [comment]
If you are still looking for assistance I would be happy to help. 

I am moving my production scripts from SOAP to rest now and should be able to pause and take notes for documentation as I go.

**Comment by aidan-casey** [comment]
@JoshNW - Welcome! Another set of eyes on this would be fantastic if you are still willing. We began the process of porting our current documentation in the README to [this website](https://anteris.dev/docs/0.3) and the source code for that is [here](https://github.com/Anteris-Dev/autotask-client-docs).

Let us know if you have any questions about using the package though. Happy to assist!
