### ISSUE TITLE
Support for Resource Impersonation

### ISSUE THREAD

**Issue by aidan-casey** [Anteris-Dev/autotask-client#20]
Right now it is impossible to impersonate resources. I would like to integrate that as a feature in this library.

Some initial thoughts for how this would look:

```php

// ID of the resource we are impersonating.
$resourceId = 12345;

// Connection details here
$client = new Anteris\Autotask\Client(.......);

// Impersonation details here
$impersonation = new Anteris\Autotask\Impersonation($resourceId, $client);

// Do whatever you want to impersonate
$impersonation->tickets()->create( $ticket );

```

Another way this could work would be:

```php

// Connection details here
$client = new Anteris\Autotask\Client(.......);

// Impersonation details here
$client->impersonate(12345)->tickets()->create( $ticket );

```

Potentially these could be the same side-by-side solution. The impersonate method would just call up an instance of the class.

**Comment by AntonioDiPassio-AppSys** [comment]
2nd way seems best to me.
Looking forward to this feature!

**Comment by JasonEde** [comment]
This would be a really nice feature to have as otherwise we'd have to do something like append creating user to the ticket description or the like.
