### ISSUE TITLE
Potential bug in create() method in Companies

### ISSUE THREAD

**Issue by Darrrren** [Anteris-Dev/autotask-client#24]
Whilst trying to test a simple create() example, I am receiving a "500 Internal Server Error" from the API Server on the Companies Endpoint.
Here is my code:
```
$testcompany = new \Anteris\Autotask\API\Companies\CompanyEntity([
    'id' => 0,
    'companyName' => 'Test Company',
    'companyType' => 1,
    'phone' => '01234 567890',
    'ownerResourceID' => 29682893
]);
try{ 
    $result = $client->companies()->create($testcompany); 
}
catch(\Exception $e) 
{ 
    dd($e); 
}
dd($result);
```
This produces the following reply from Autotask:
```
GuzzleHttp\Exception\ServerException {#381 ▼
  -request: GuzzleHttp\Psr7\Request {#370 ▶}
  -response: GuzzleHttp\Psr7\Response {#378 ▶}
  -handlerContext: []
  #message: """
    Server error: `POST https://webservices16.autotask.net/ATServicesRest/v1.0/Companies` resulted in a `500 Internal Server Error` response:
    {"errors":["An unexpected error has occurred.  If the problem persists, please contact Autotask Support and reference Er (truncated...)
    """
  #code: 500
  #file: "C:\wamp64\AUTONOX\autonoxclient\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php"
  #line: 113
  trace: {▶}
}
```
I've been able to create() Contacts no problem at all so I'm hoping I'm just missing something simple on this perticular endpoint or method. I've checked the API documentation to make sure all the minimum required fields are present and in the correct format but to no avail. As you can see the error is truncated so I can't report the error number to Datto and the information which we can read is just a generic "error" message from their server so it's no help really.  I'm stuck.. Time for coffee!

**Comment by Darrrren** [comment]
To help illustrate the problem here is the newly instantiated Company, with all the `null` fields removed before the create() method is called:
```
Anteris\Autotask\API\Companies\CompanyEntity {#363 ▼
  +companyName: "Test Company"
  +companyType: 1
  +id: 0
  +ownerResourceID: 29682893
  +phone: "01234 567890"
}
```

**Comment by Darrrren** [comment]
More info on this...
I've been able to work around the error being truncated by catching a RequestException instead of an Exception like this:
```
catch(RequestException $e)
{
    dd($e->getResponse()->getBody()->getContents());
}
```
Now I can read the full body of the error message which is:
```
{"errors":["An unexpected error has occurred.  If the problem persists, please contact Autotask Support and reference Error ID: 842583.","If the problem persists, please contact Autotask Support and reference Error ID: 842583."],"errorId":842583}
```
I'll contact Datto and see what they say about it.  Still drinking coffee on this one :-(

**Comment by Darrrren** [comment]
And with a bit more reading, I can now see the request sent to the server and the full response using the following catch:
```
catch(\Guzzlehttp\Exception\ServerException $e)
{
    dump (\Guzzlehttp\Psr7\str($e->getRequest()));
    if ($e->hasResponse()) {
          dump (\Guzzlehttp\Psr7\str($e->getResponse()));
    }
}
```
So the request that was sent was:
```
"""
POST /ATServicesRest/v1.0/Companies HTTP/1.1
Username: XX
Secret: XX
APIIntegrationcode: XX
User-Agent: GuzzleHttp/6.5.5 curl/7.70.0 PHP/7.4.8
Content-Type: application/json
Host: webservices16.autotask.net

{"additionalAddressInformation":null,"address1":null,"address2":null,"alternatePhone1":null,"alternatePhone2":null,"apiVendorID":null,"assetValue":null,"billingAddress1":null,"billingAddress2":null,"billToAdditionalAddressInformation":null,"billToAddressToUse":null,"billToAttention":null,"billToCity":null,"billToCompanyLocationID":null,"billToCountryID":null,"billToState":null,"billToZipCode":null,"city":null,"classification":null,"companyName":"Test Company","companyNumber":null,"companyType":1,"competitorID":null,"countryID":null,"createDate":null,"createdByResourceID":null,"currencyID":null,"fax":null,"id":0,"impersonatorCreatorResourceID":null,"invoiceEmailMessageID":null,"invoiceMethod":null,"invoiceNonContractItemsToParentCompany":null,"invoiceTemplateID":null,"isActive":null,"isClientPortalActive":null,"isEnabledForComanaged":null,"isTaskFireActive":null,"isTaxExempt":null,"lastActivityDate":null,"lastTrackedModifiedDateTime":null,"marketSegmentID":null,"ownerResourceID":29682893,"parentCompanyID":null,"phone":"01234 567890","postalCode":null,"quoteEmailMessageID":null,"quoteTemplateID":null,"sicCode":null,"state":null,"stockMarket":null,"stockSymbol":null,"surveyCompanyRating":null,"taxID":null,"taxRegionID":null,"territoryID":null,"webAddress":null,"userDefinedFields":null} ◀
"""
```
I've obviously taken out the sensitive fields and replaced them with "XX". And the full response from the server was:
```
"""
HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 246
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
begin-tick: 322588093
X-Powered-By: ASP.NET
Content-Security-Policy: default-src 'self' https: *;script-src 'self' 'unsafe-inline' 'unsafe-eval' https: *;style-src 'self' 'unsafe-inline';img-src 'self' https://walkme.psa.datto.com/Images/ data: https://www.datto.com/img/ ◀
Date: Wed, 16 Sep 2020 15:45:47 GMT

{"errors":["An unexpected error has occurred.  If the problem persists, please contact Autotask Support and reference Error ID: 842597.","If the problem persists, please contact Autotask Support and reference Error ID: 842597."],"errorId":842597} ◀
"""
```

**Comment by aidan-casey** [comment]
@Darrrren - Wow, thanks for the detailed debugging here! Just seeing this now and I am going to take a look in my sandbox environment. The API _should_ return a 4xx error if it is an issue with how the request is being made and a 5xx error if it is an issue with how the server parsed it, but I do not fully trust that to be the case.

Side note, perhaps when we implement #23 we should work on presenting errors in a more helpful manner.

**Comment by aidan-casey** [comment]
This looks to be an Autotask bug. Even attempting to create a company through Swagger results in this error. I have reached out to a contact there to see if they can clue me in on what those errors reference.

Thanks for reporting @Darrrren, I will keep this issue open and updated while I wait to hear more.

**Comment by Darrrren** [comment]
I'll raise a ticket with them tomorrow as well. I had a conference call with the integrations team about something else today in fact and I did mention it but I must admit, I told them it was probably my bad coding :-)

**Comment by Darrrren** [comment]
Temporary workaround:

By adding `'billToAddressToUse' => 1` to your CompanyEntity instantiation (in my case $testcompany above), the create() method will work as expected. 

This shouldn't cause too much of an issue whilst we're waiting for a fix as this non required(?!?) variable is associated with invoicing preferences in the UI. Here is a excerpt from the documentation around this: 

> BillToAddressToUse and the related address fields in the Company entity are associated with the account Invoice Preferences. In the UI, Invoice Preferences are created separately from the Company entity and the Company entity must exist before they can be added. When using create in the API, no account exists yet, there is no BillToAddressToUse value, so the BillToAddressToUse field will always default to the selection “Use Company Address” (1), and related fields will always default to the account address information. Any values provided for the related fields on create are ignored.
> When BillToAddressToUse = 1, CompanyAddress, it can only be changed to 2, CompanyBilling, via the UI.   
 
I would close this one Aidan as Andy's fix appears to work ok :-)

**Comment by aidan-casey** [comment]
Thanks @Darrrren! I am going to close this issue as recommended. I appreciate the detail!
