### ISSUE TITLE
"itemId" not returned when using create()

### ISSUE THREAD

**Issue by Darrrren** [Anteris-Dev/autotask-client#25]
When creating new Companies, the Autotask API upon successful creation, returns the ID of the newly created record. Details can be found here: [https://ww16.autotask.net/help/DeveloperHelp/Content/AdminSetup/2ExtensionsIntegrations/APIs/REST/API_Calls/REST_Creating_Resources.htm](url). 

I can't seem to find a way to retrieve that ID from the guzzle Response object returned from the query.  I've tried `->getBody()` and there is no getResponse() method so I'm stuck.

Here is the full response from the server upon a successful completion of a new CompanyEntity:
```
GuzzleHttp\Psr7\Response {#1578 ▼
  -reasonPhrase: "OK"
  -statusCode: 200
  -headers: array:10 [▼
    "Cache-Control" => array:1 [▼
      0 => "no-cache"
    ]
    "Pragma" => array:1 [▼
      0 => "no-cache"
    ]
    "Content-Length" => array:1 [▼
      0 => "14"
    ]
    "Content-Type" => array:1 [▼
      0 => "application/json; charset=utf-8"
    ]
    "Expires" => array:1 [▼
      0 => "-1"
    ]
    "Server" => array:1 [▼
      0 => "Microsoft-IIS/8.5"
    ]
    "begin-tick" => array:1 [▼
      0 => "747226687"
    ]
    "X-Powered-By" => array:1 [▼
      0 => "ASP.NET"
    ]
    "Content-Security-Policy" => array:1 [▼
      0 => "default-src 'self' https: *;script-src 'self' 'unsafe-inline' 'unsafe-eval' https: *;style-src 'self' 'unsafe-inline';img-src 'self' https://walkme.psa.datto.com/Images/ data: https://www.datto.com/img/ ◀"
    ]
    "Date" => array:1 [▼
      0 => "Mon, 21 Sep 2020 13:43:06 GMT"
    ]
  ]
  -headerNames: array:10 [▼
    "cache-control" => "Cache-Control"
    "pragma" => "Pragma"
    "content-length" => "Content-Length"
    "content-type" => "Content-Type"
    "expires" => "Expires"
    "server" => "Server"
    "begin-tick" => "begin-tick"
    "x-powered-by" => "X-Powered-By"
    "content-security-policy" => "Content-Security-Policy"
    "date" => "Date"
  ]
  -protocol: "1.1"
  -stream: GuzzleHttp\Psr7\Stream {#1575 ▼
    -stream: stream resource @17 ▼
      wrapper_type: "PHP"
      stream_type: "TEMP"
      mode: "w+b"
      unread_bytes: 0
      seekable: true
      uri: "php://temp"
      options: []
    }
    -size: null
    -seekable: true
    -readable: true
    -writable: true
    -uri: "php://temp"
    -customMetadata: []
  }
}
``` 
We can see the `reasonPhrase` and `statusCode` but I just can't seem to find the "itemId" returned by the server.

When I create the same company manually using Postman, I get a 200 reply plus: 

```
{
    "itemId": 217
}
```
>where 217 is the ID of the newly created record in the Autotask database

Any ideas?

**Comment by aidan-casey** [comment]
Yeah, so this is something we need to add to the roadmap for our next major version. I would like to return an entity with the item ID in the future.

In the meantime, however, you _should_ be able to do the following:

```php

// Make the request which returns a Guzzle response object
$response = $client->companies()->create( $companyEntity );

// Get the response and decode the JSON data to an array
$responseArray = json_decode($response->getBody(), true);

if (! isset($responseArray['itemId']) {
    throw new \Exception('There was an error creating that company!');
}

echo $responseArray['itemId'];

```

The important part thing to know is that the create method returns a Guzzle response and that the response needs to be cast to a string and decoded from JSON.

If this isn't working for you, let me know, that would potentially be package problem, but we have been using the above for our own production-level packages.

**Comment by Darrrren** [comment]
Ahhh fantastic thanks, That explains it, I'll give it a spin now and see if it works :-D

**Comment by aidan-casey** [comment]
Hey @Darrrren, going to close this issue. Let me know if you have further troubles!

**Comment by Darrrren** [comment]
No your suggestion works a treat thanks
