### ISSUE TITLE
Creation of AttachmentNestedAttachment

### ISSUE THREAD

**Issue by AntonioDiPassio-AppSys** [Anteris-Dev/autotask-client#29]
Hi there

AttachmentNestedAttachmentService::create() uses an incorrect endpoint.

This is what it should be:

```
public function create(AttachmentNestedAttachmentEntity $resource): Response
    {
        $parentID = $resource->parentID;
        return $this->client->post("Attachments/$parentID/NestedAttachments", $resource->toArray());
    }
```

Tested on API 2020.3

**Comment by AntonioDiPassio-AppSys** [comment]
Same for TicketNoteAttachmentService::create()

```
    public function create(TicketNoteAttachmentEntity $resource): Response
    {
        $parentID = $resource->parentID;
        return $this->client->post("TicketNotes/$parentID/Attachments", $resource->toArray());
    }

```

**Comment by aidan-casey** [comment]
@AntonioDiPassio-AppSys - Thanks for this! Definitely a bug that we will begin working on ASAP.

Do you mind my asking, how has your experience with this package been otherwise?

**Comment by AntonioDiPassio-AppSys** [comment]
@aidan-casey - Can't complain really. I just started using it two weeks ago, and so far it does what I need it to do. Only thing missing right now is the possibility for resource impersonation, but there's another issue (#20) open for that. But to be fair, I'm only using it for ticket related stuff (tickets, ticket notes, ticket attachments, ticket time entries).

**Comment by aidan-casey** [comment]
@AntonioDiPassio-AppSys - Can you clarify on the ticket notes attachments? According to swagger, it looks like it is correct. 

https://webservices2.autotask.net/atservicesrest/swagger/ui/index#/TicketNoteAttachmentsChild

**Comment by AntonioDiPassio-AppSys** [comment]
Indeed, Swagger shows the correct endpoint to use: TicketNotes/$parentId/Attachments

But in your code TicketNoteAttachmentService::create() (line 38), you have:

public function create(TicketNoteAttachmentEntity $resource): Response
    {
        return $this->client->post("TicketNoteAttachments", $resource->toArray());
    }

**Comment by aidan-casey** [comment]
Feel free to take v0.5.0 for a spin. This should now be fixed.
