### ISSUE TITLE
User Defined Fields

### ISSUE THREAD

**Issue by Darrrren** [Anteris-Dev/autotask-client#34]
I need some examples of how to set UDF's for entities that have the correct UDF's configured in Autotask, but have not yet had one set and so the `companies()->query()` service returns an empty array in `userDefinedFields`.  A more detailed explanation can be found on the Discord channel!

For example, I have a UDF in the Companies entity called "ExternalID" and the query returns:
```
$customer = $client->companies()->findByID(224);
dd($customer);

Anteris\Autotask\API\Companies\CompanyEntity {#1323 ▼
  ...
  +userDefinedFields: []
  ...
}
```
for a Company that has not yet had any of its UDF's set... I want to set the "ExternalID" UDF but when I try to set it like this:
```
$customer->userDefinedFields['ExternalID'] = "99999999";
```
and save it, I get this error from the API:
```
{"errors":["An unexpected error has occurred.  If the problem persists, please contact Autotask Support and reference Error ID: 54634.","If the problem persists, please contact Autotask Support and reference Error ID: 54634."],"errorId":54634}
```
Any ideas anyone?  Monitoring this thread and Discord for any help thanks.

**Comment by aidan-casey** [comment]
I think you will want to try something like this:

```php

use Anteris\Autotask\Support\UserDefinedFields\UserDefinedFieldEntity;

$customer->userDefinedFields[] = new UserDefinedFieldEntity([
    'name' => 'ExternalID',
    'value' => '99999999',
]);
```

**Comment by Darrrren** [comment]
Perfect Aidan thanks, I'll update the Discord thread!

**Comment by aidan-casey** [comment]
Thanks! Glad you got it sorted! 🙂
