### ISSUE TITLE
Autotask API Bug - QuoteItems.sortOrderID

### ISSUE THREAD

**Issue by Darrrren** [Anteris-Dev/autotask-client#38]
Heads up guys! The 2020.3 release gave us a new field: `sortOrderID` in QuoteItems.

The Autotask documentation does not say it is a required field and does not give us any related Entity to reference so it's not entirely clear how to use this field or exactly what it's purpose is. 

When instantiating a new instance of QuoteItems using this package, the sortOrderID field is initially set to `null` if it is not set which is correct and is sent into the POST method along with all the other fields. However, the API will fail to create a new QuoteItem and will throw the following 500 error:
```
{
    "errors": [
        "An unexpected error has occurred.  If the problem persists, please contact Autotask Support and reference Error ID: 57492.",
        "If the problem persists, please contact Autotask Support and reference Error ID: 57492."
    ],
    "errorId": 57492
}
```

Steps to reproduce:

Using Postman, POST into the following URL with the correct Authorisation Headers:
`https://webservices19.autotask.net/atservicesrest/v1.0/Quotes/{$quoteID}/Items/`

and send the following payload:

```
{
    "averageCost": null,
    "chargeID": null,
    "description": null,
    "expenseID": null,
    "highestCost": null,
    "id": 0,
    "internalCurrencyLineDiscount": null,
    "internalCurrencyUnitDiscount": null,
    "internalCurrencyUnitPrice": null,
    "isOptional": false,
    "isTaxable": null,
    "laborID": null,
    "lineDiscount": 0.0,
    "markupRate": null,
    "name": "Test Service",
    "percentageDiscount": 0.0,
    "periodType": null,
    "productID": null,
    "quantity": 2.0,
    "quoteID": {$quoteID},
    "quoteItemType": 11,
    "serviceBundleID": null,
    "serviceID": {$serviceID},
    "shippingID": null,
    "sortOrderID": null,
    "taxCategoryID": null,
    "totalEffectiveTax": null,
    "unitCost": null,
    "sortOrderID": null,
    "unitDiscount": 0.0,
    "unitPrice": 2000.0
}
```
where `{$quoteID}` is the ID of the quote you want to add the item to and `{$serviceID}` is the correct ID for the desired Autotask Service in this example.

**Workaround:**
It would appear that the API doesn't like `sortOrderID` being set as `null`.  Therefore we MUST set an integer value every time we POST a new QuoteItem, using something like `sortOrderID = 1`.  A dirty #Hack I know, but it is the only way I could get around the problem.  If anybody knows exactly what this field is for, or the implication of setting the value to `1`, please let us know.

**Comment by aidan-casey** [comment]
@Darrrren - Thanks for providing all the detail on this! In this release `lineItemID` for `BillingItem` entities was also changed to `sortOrderID`. The [official](https://www.autotask.net/help/DeveloperHelp/Content/AdminSetup/2ExtensionsIntegrations/APIs/REST/Entities/BillingItemsEntity.htm) Autotask description for that is:

> When multiple BillingItems that are associated with the same internalCurrencytaxDollars share the same lineItemID, those items are grouped.It is possible for a BillingItem to have a unique lineItemID and still be "grouped" in a group of one item. To confirm the group status of a BillingItem, refer to Invoice.invoiceEditorTemplateID and the InvoiceTemplate.groupBy value.

When it comes to quote items, I _believe_ that `sortOrderID` determines the order of a line item. For example, if I had the following two entities, "Item A" would actually be the second line item (the other fields are pulled out purely for visibility). There is a chance, however, that it is used for the same grouping effect described above.

```json
{
    "name": "Item A",
    "sortOrderID": 2
}

{
    "name": "Item B",
    "sortOrderID": 1
}
```

There is probably some room for improvement here by default the value to 0.

**Comment by Darrrren** [comment]
Yep that would fix it for now I'm sure.  I've told the Integrations team so hopefully it'll get picked up at their end.  
On a different topic, I would love your thoughts on my UDF question on the Discord channel :-)

**Comment by aidan-casey** [comment]
I got you. Another area we need to improve, but check out my response and let me know your thoughts. 🙂
