### ISSUE TITLE
companyCategoryID not found

### ISSUE THREAD

**Issue by s7thamon** [Anteris-Dev/autotask-client#39]
Assuming Autotask has made some updates to their API as I have not changed any code on my end. Now getting the following error looking up companies:

```
DataTransferObjectError
Public properties `companyCategoryID` not found on Anteris\Autotask\API\Companies\CompanyEntity
```

**Comment by aidan-casey** [comment]
@s7thamon - Thank you for catching this and submitting your PR. The package is updated with your changes on release `v0.5.1`.
