### ISSUE TITLE
BillingItems Entity missing new variables

### ISSUE THREAD

**Issue by Darrrren** [Anteris-Dev/autotask-client#42]
After the recent 2021.1.7 update, the `BillingItems` entity now has fields missing and this has broken several of the methods associated with this endpoint.  The missing variables should go somewhere in here:
https://github.com/Anteris-Dev/autotask-client/blob/0f640a338859e600eb09ce4a48fbb6e2d4e1df45/src/API/BillingItems/BillingItemEntity.php#L61
and the missing fields are as follows:
```php
public $contractServiceID;
public $contractServiceBundleID;
public $contractServiceAdjustmentID;
public $contractServiceBundleAdjustmentID;
public $contractServiceBundlePeriodID;
public $contractServicePeriodID;
```
Details of the changes in the last update can be found here: [https://ww19.autotask.net/help/DeveloperHelp/Content/APIs/REST/General_Topics/REST_API_Revision_History.htm](url)

For the benefit of the reader, the symptoms, in Laravel, are as follows.  Try and retrieve BillingItems associated with an invoice:
```php
$rows = $client->billingItems()->query()->where('invoiceID','eq',$invoice->id)->get();
```
and receive the following exception:
```
Spatie\DataTransferObject\DataTransferObjectError
Public properties `contractServiceAdjustmentID`, `contractServiceBundleAdjustmentID`, `contractServiceBundleID`, `contractServiceBundlePeriodID`, `contractServiceID`, `contractServicePeriodID` not found on Anteris\Autotask\API\BillingItems\BillingItemEntity
```
Unlike yesterday where I posted an issue report before doing an update (!), this one is legit ;-)

**Comment by aidan-casey** [comment]
Thank you for reporting this, @Darrrren. This is fixed by #43.
