### ISSUE TITLE
Overview page needs review of how to use comparison operators in the where() method

### ISSUE THREAD

**Issue by optmsp** [Anteris-Dev/autotask-client#44]
I found myself jumping between documentation and notes, and I think it would be great to have this on your overview page under the section on where(). I'm happy to contribute with whatever method you prefer, but just in case the markdown is below. I'm using this lib in a new project, so am happy to contribute further to filling out the docs if needed.

...

### Comparison operators for where()

Following are the comparison operators and examples of how to use them with this library using the where() method.

| Keyword | Description | Example |
| ------- | ----------- | -------- |
| eq | Equals | where('companyName', 'eq', 'Test Company')
| noteq | Not Equals | where('companyName', 'noteq', 'Test Company')
| gt | Greater Than | where('id', 'gt', '10304303')
| gte | Greater Than or Equals | where('id', 'gte', '10304303')
| lt | Less Than | where('id', 'lt', '10304303')
| lte | Less Than or Equals | where('id', 'lte', '10304303')
| in | In Set | where('companyName', 'in', ['Company 1, LLC', 'Company 2, LLC', 'Company 3, LLC'])
| notIn | Not In Set | where('companyName', 'notIn', ['Company 1, LLC', 'Company 2, LLC', 'Company 3, LLC'])
| exist | Field is not null/empty | where('billingAddress2', 'exists')
| notExist | Field is null/empty | where('billingAddress2', 'notExist')
| beginsWith | Field text begins with.. | where('companyName', 'beginsWith ', 'Test')
| endsWith | Field text ends with.. | where('companyName', 'endsWith', 'Company')
| contains | Field contains.. | where('contains ', 'contains', 'st Co')

**Comment by optmsp** [comment]
Or via pastebin: https://pastebin.com/RfJtar1P

**Comment by aidan-casey** [comment]
I'd accept a PR for this if you want to submit one. 🙂
