### ISSUE TITLE
date comparison in where() acts like a gte instead of a gt comparison?

### ISSUE THREAD

**Issue by optmsp** [Anteris-Dev/autotask-client#45]
so.. i think i'm doing a query wrong on autotask or something else is happening. i have a local store of my companies in mysql. i want to fetch updates from autotask, so im looking for the newest last_modification in my local table and then sending a query to autotask for any company where company.lastTrackedModifiedDateTime > max(local.last_mod) more or less. but i keep getting 1 entry back.. same entry every time. i can't figure it out.

here is the query:
```
$autotaskQuery = $this->autotaskClient
            ->companies()
            ->query()
            ->where('lastTrackedModifiedDateTime', 'gt', $newestLastModificationDateTime);
```

where:
`$newestLastModificationDateTime=2021-07-26 21:15:08`

and i get this entry back:
`processing XXXXXX (30196526)- lastTrackedModifiedDateTime: 2021-07-26 21:15:08 - createDate: 2014-08-20 22:04:52`
which is the newest last_mod in autotask that i was using in my compare. i would expect the results to not include this entry for a gt but to include it for a gte.

**Comment by aidan-casey** [comment]
Hey there, @optmsp! Sorry to hear about the trouble with dates, that is an interesting issue!

There are a couple things you might double check:

1. Autotask accepts the date format of `yyyy-mm-ddThh:mm:ss.ms` so you may want to try formatting your comparison value accordingly. This could be the reason the comparison is not working correctly.

2. Autotask stores and returns all dates in UTC, I'm not sure if you're using a `DateTime` object or just a string, so just double check that you are not sending the date in a different timezone.

Do let me know how it works out, if this continues to be an issue there's always the chance that it's an Autotask bug, which we can report to them.
