### ISSUE TITLE
Loop function add to array

### ISSUE THREAD

**Issue by s7thamon** [Anteris-Dev/autotask-client#48]
Having difficulty figuring out why the loop function cannot add fields to an array

```
$autotaskInvoices = $autotaskClient
  ->invoices()
  ->query()
  ->where('invoiceDateTime', 'gte', Carbon::now()->subYear());

$invoices = [];

$autotaskInvoices->loop(function (InvoiceEntity $invoice) use ($invoices) {
  $invoices[] = [
    'id' => $invoice->id,
    'companyID' => $invoice->companyID,
    'invoiceTotal' => $invoice->invoiceTotal,
    // if I dump here, the $invoices array is populated by the entity
  ];
});

return $invoices;
```

$invoices will continue to return empty, however if I dump the variable inside the loop function I can see it's populated. Relatively confused by this behavior, not sure what's going on. The end goal is to simply return an array of some mapped values.

**Comment by aidan-casey** [comment]
Hey @s7thamon! What you're getting in your callback is a _copy_ of your `$invoices` variable at a different location in memory. You need to pass `$invoices` as a reference to update the same value in memory.

To do this, just add an ampersand before the variable in the use statement: `use (&$invoices)`

For more information, see [here](https://www.php.net/manual/en/language.references.pass.php).

Thanks!

**Comment by s7thamon** [comment]
Oh duh 🙃 - thank you for that.

**Comment by aidan-casey** [comment]
No problem! 🙂
