### ISSUE TITLE
Best way to get ticket number of new ticket just created?

### ISSUE THREAD

**Issue by JasonEde** [Anteris-Dev/autotask-client#52]
I've built a new ticket and can create it with 
$newtick=$client->tickets()->create($ticket);

However, I can't see a simple way to get the TicketNumber of this new ticket without then doing a search for say the title created on this date. Am I missing something? There doesn't seem to be anything returned in $newtick that I can use.

Realise this is more an Autotask API qn than how it's implemented here.

**Comment by aidan-casey** [comment]
Hey @JasonEde!

Something like this should work:

```php
// Make the request which returns a Guzzle response object
$response = $client->tickets()->create($ticketEntity);

// Get the response and decode the JSON data to an array
$responseArray = json_decode($response->getBody(), true);

if (! isset($responseArray['itemId']) {
    throw new \Exception('There was an error creating that ticket!');
}

$ticket = $client->tickets()->findById($responseArray['itemId']);
```

When we update this package we will provide a better way to get at that, as we recognize that can take some effort. 🙂
