### ISSUE TITLE
Change request used by query from GET to POST

### ISSUE THREAD

**Issue by AntonioDiPassio-AppSys** [Anteris-Dev/autotask-client#53]
Right now, the client uses GET requests to query the API.

This causes problems when the query params are very big. Probably because a GET request is limited to around 2048 chars, and it just gets truncated at the server.

For example, performing a contact query for multiple email adresses

`$paginator = Autotask::contacts->query()->where('emailAddress','in',$emails)->paginate();`

where $emails is an array with a lot of elements.

**Comment by optmsp** [comment]
Also having this issue. Did you end up writing an alternate to use the POST method supported by Autotask API for queries?

**Comment by AntonioDiPassio-AppSys** [comment]
No, I just made several queries instead.

**Comment by optmsp** [comment]
Okay. I have a few queries out to @aidan-casey for his autotask-client-generator repo. I have it on my todos to add support for POST queries, which the Autotask API supports. Once that is done, we should be able to send very large queries as needed.

**Comment by aidan-casey** [comment]
@AntonioDiPassio-AppSys, @optmsp - I do apologize for the neglect this package has received. The original implementation of data transfer objects as the response has proved to be a maintenance burden as my time has become more limited.

It is still on my backlog to implement a new version of this package, but in the meantime I will accept PRs to the generator repository and re-generate this package as needed.

**Comment by optmsp** [comment]
No sweat @aidan-casey, thanks for the library!
