### ISSUE TITLE
Exception 'Error' with message 'Call to undefined method Anteris\Autotask\Client::timeOffRequests()'

### ISSUE THREAD

**Issue by optmsp** [Anteris-Dev/autotask-client#56]
I keep getting this error trying to retrieve TimeOffRequests from the Autotask API. I have verified that my code works if I replace timeOffRequests() with resources().

Fails:

```
        $timeOffQuery = $this->autotaskClient->timeOffRequests()->query()
                            ->where('resourceID', 'eq', $resourceID)
```

Succeeds:

```
        $timeOffQuery = $this->autotaskClient->resources()->query()
                            ->where('id', 'eq', $resourceID);
```

The error I am getting is:

`Exception 'Error' with message 'Call to undefined method Anteris\Autotask\Client::timeOffRequests()'`

I assume I'm doing something silly. Any ideas on this one?

**Comment by optmsp** [comment]
Anybody have this issue with timeOffRequests()?

**Comment by aidan-casey** [comment]
@optmsp - Is this still an issue for you?
