### ISSUE TITLE
Public properties not found on Anteris\Autotask\API\ConfigurationItems\ConfigurationItemEntity

### ISSUE THREAD

**Issue by PeterVoskuilen** [Anteris-Dev/autotask-client#57]
When getting the ConfigurationItems from AutoTask using:

`$page = $this->atClient->ConfigurationItems()->query()->where('id', 'exist')->paginate();`

an error is thrown.

Public properties `dattoNICSpeedKilobitsPerSecond`, `dattoZFSVersionID`, `rmmDeviceAuditSNMPContact`, `rmmDeviceAuditSNMPLocation`, `rmmDeviceAuditSNMPName`, `rmmDeviceUID` not found on Anteris\Autotask\API\ConfigurationItems\ConfigurationItemEntity

When looking in ConfigurationItemEntity.php I see the property is there but captials are not correct / in sync with API.

In AT API dattoNICSpeedKilobitsPerSecond is used
In ConfigurationItemEntity.php public ?int $dattoNicSpeedKilobitsPerSecond; is used.

I'm using https://webservices4.autotask.net/ATServicesRest/ 

when changing the variables in ConfigurationItemEntity.php the issue is resolved for me.

**Comment by aidan-casey** [comment]
@PeterVoskuilen - This should be resolved in the latest release. Can you confirm?
