### ISSUE TITLE
syntax error, unexpected token \"[\", expecting variable

### ISSUE THREAD

**Issue by qaxperts** [Anteris-Dev/autotask-client#59]
syntax error, unexpected token \"[\", expecting variable
anteris-dev/autotask-client/src/API/TicketNoteAttachments/TicketNoteAttachmentEntity.php  "line": 20

public ?byte[] $data;   = This is not working with php 8.0

public $id;
public ?string $data;

Both id and data declared twice in TicketNoteAttachmentEntity.php file

**Comment by aidan-casey** [comment]
@qaxperts - Should be fixed in the latest release. Can you confirm?
