### ISSUE TITLE
TicketAttachments()->findById expects TicketAttachmentEntity, but TicketAttachmentCollection returned

### ISSUE THREAD

**Issue by msullivanJIT** [Anteris-Dev/autotask-client#64]
$client->TicketAttachments()->findById($id);

TicketAttachmentService->findByID expects TicketAttachmentEntity, but TicketAttachmentCollection is returned from Autotask. Changing the entity type to TicketAttachmentCollection seems to allow attachments using findById().

**Comment by aidan-casey** [comment]
@msullivanJIT - Can you edit that method and dump out the contents of that collection? That endpoint shouldn't be returning collections at all.
