### ISSUE TITLE
Autotask\API\TimeEntries\TimeEntriesEntity::resourceID to be of type integer, instead got value null, which is NULL..

### ISSUE THREAD

**Issue by Niels-Kolkman** [Anteris-Dev/autotask-client#65]
![image](https://user-images.githubusercontent.com/60409592/175875484-520aad16-1e42-45fa-bd94-4db5f4b4628d.png)

While trying to get all TimeEntries as a test call im getting the error that resourceID is null
![image](https://user-images.githubusercontent.com/60409592/175875740-ac98ccb9-0993-4a96-9cc4-e2c0b6954e33.png)

error:
![image](https://user-images.githubusercontent.com/60409592/175876240-f0d352c6-1f37-4a2d-b9b6-2d704a358e07.png)

**Comment by Niels-Kolkman** [comment]
`Public properties `createdByContactID`, `creatorResourceID`, `description`, `lastActivityDate`, `noteType`, `publish`, `title` not found on Autotask\API\TimeEntries\TimeEntriesEntity`
 
 when i make resourceID nullable.
 
I think this entity might need an update

**Comment by aidan-casey** [comment]
@Niels-Kolkman - Can you edit the query builder and dump the raw response for me?
