### ISSUE TITLE
Error when trying to change ticket status for a company with multiple locations

### ISSUE THREAD

**Issue by JasonEde** [Anteris-Dev/autotask-client#70]
I'm trying to change the status of a ticket after adding a note to the ticket. I can add the note fine. For 1 company (that I've noticed so far) when I try to change the status using the following code

                
                $ticket=$client->tickets()->findById($ticketID);
                $ticket->status=19;

                $client->tickets()->update($ticket);
               
I receive an error back:
"The companyLocationID[XXX] cannot be associated with the Ticket. The Ticket and CompanyLocation must have the same companyID."

On this ticket CompanyID is set to the details of the sub-site with company location ID pointing to CompanyLocation where the company ID is set to the parent company ID. 

There are no errors within the autotask GUI for this ticket or the linking to the parent company, but errors just appear when i try to change the ticket status. 

Is it taking my above code as trying to change the companyLocationID or companyID and if so am I best changing the status another way? Is it not liking that the location is a sub-site of the main company? If so is there another way around this?

**Comment by JasonEde** [comment]
I have a feeling I'm sending too much data back and just need to submit the changes, but if I say try and construct a new entity to change the status
$ticket= new Anteris\Autotask\API\Tickets\TicketEntity([
        'id'=> XXXX,
        'status'=> 19,
         ]);

then I get errors of PHP Fatal error:  Uncaught Spatie\DataTransferObject\DataTransferObjectError: The following invalid types were encountered:
expected `Anteris\Autotask\API\Tickets\TicketEntity::companyID` to be of type `integer`, instead got value `null`, which is NULL.
expected `Anteris\Autotask\API\Tickets\TicketEntity::priority` to be of type `integer`, instead got value `null`, which is NULL.
expected `Anteris\Autotask\API\Tickets\TicketEntity::title` to be of type `string`, instead got value `null`, which is NULL.

I don't want to change these values so is there a way of just changing the status without having to get the entire ticket contents? The API documentation implies I just need to send the changes along with the id of the item to make the change.

**Comment by Darrrren** [comment]
Have you checked with Postman that the record actually exists?  If it does, you could try searching for the Ticket using `where('id','eq',$ticketID)` instead of `findById()` instead.

I seem to remember stumbling across a strange issue in recent releases whereby `findById()` doesn't work correctly when the method can't find the record. Instead of returning null or an empty set, it throws an exception or an error which could be your issue.

**Comment by JasonEde** [comment]
It seems this issue affects just one client. I've replicated the issue using swagger so logged a ticket with autotask/datto.
