### ISSUE TITLE
Compound queries

### ISSUE THREAD

**Issue by JasonEde** [Anteris-Dev/autotask-client#72]
I'm trying to get a compound query working and its having issues.

I'm trying to look up tickets where companyID eq X AND (status noteq 5 OR (status eq 5 and lastActivityDate gte current_date-7days) )

I've tried

```php
$ticket_query= $connection
    ->tickets()
    ->query()
    ->where(
        function($q) use ($account_id, $final_date) {
            return $q
                ->where('companyID', 'eq', $account_id)
                ->where('status', 'noteq', 5, false, 'OR')
                ->where('status', 'eq', 5)
                ->where('lastActivityDate', 'gte', $final_date);
    });
```

and I've tried moving the OR around to statement below, but it's ignoring the second part of the query. I feel like I'm not far off and I know I could do separate queries, but trying to minimise the queries as it's part of a web page

**Comment by aidan-casey** [comment]
@JasonEde - Untested, but this is the direction you should be taking:

```php
$result = $connection
    ->tickets()
    ->query()
    ->where('companyID', 'eq', $account_id)
    ->orWhere(
        fn ($q) => $q
            ->where('status', 'noteq', 5)
            ->where(
                fn ($q) => $q
                    ->where('status', 'eq', 5)
                    ->where('lastActivityDate', 'gte', $final_date)
            )
    );
```

You can convert short functions to functions if needed. 🙂
