### ISSUE TITLE
API calls not working on Rocky/Centos 9. Fails with ssl error

### ISSUE THREAD

**Issue by JasonEde** [Anteris-Dev/autotask-client#75]
Trying to move to a new server on RockyLinux 9 (php 8.0.20) and it seems it's not liking the curl calls for some reason.

PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 35: error:0A000152:SSL routines::unsafe legacy renegotiation disabled (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by JasonEde** [comment]
I managed to get this to work by changing /etc/pki/tls/openssl.conf to show 

[ crypto_policy ]

Options = UnsafeLegacyRenegotiation
.include = /etc/crypto-policies/back-ends/opensslcnf.config

I'm not happy doing this unless it's just that autotask is insisting on old protocols?

**Comment by PaulMcITS** [comment]
It appears autotask is only supporting TLSv1.2 at the moment, so the only option is to add this to openssl.conf at the moment

**Comment by aidan-casey** [comment]
Unfortunately this is the case. This broke our automatic generator (based on GitHub actions) as well, hence the lack of updates. 😅
