### ISSUE TITLE
v0.5.5 not compatible anymore with PHP7.4

### ISSUE THREAD

**Issue by nedvice-sv** [Anteris-Dev/autotask-client#78]
As the title said; since the addition of the collections its not possible to run with PHP7.4 anymore.

See the following file: https://github.com/illuminate/collections/blob/v9.0.0/composer.json

I know that we should update to PHP8+ but some projects aren't working anymore and aren't moving as fast as we hoped.
Versioning at the other hand in this matter is WRONG. Minor versions should be backwards compatible. Major versions shouldn't. We aren't even on a 'major' version just yet.

I'm forced to update the project to 8+ before I can re-use this package right now (or I have to fork this)

Please update the package then so only 8+ can be used.
Thanks

**Comment by aidan-casey** [comment]
Hey @nedvice-sv,

This project adheres to SemVer. SemVer specifically states that an update of dependencies without a change in the public API is not a breaking change (see [here](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api)). This is widely accepted amongst many people in the development community as well, for example, [here](https://sebastiandedeyne.com/composer-semver-and-underlying-dependency-changes).

PHP 7.4 was deprecated in November of 2022. We will not be reverting this decision, so you are more than welcome to either fork this package, or pin your dependencies to v0.5.4.

We are currently working on a rewrite of this package that will be released in a few weeks. This rewrite will require PHP 8.2.

P.S., I would like to point you in the direction of [RectorPHP](https://github.com/rectorphp/rector). All of our production projects are running on the latest version of PHP (8.2) and we use Rector to help us with our upgrades.

**Comment by nedvice-sv** [comment]
@aidan-casey What I meant to say was that your composer.json and your readme aren't up2date anymore since it states that: it can have this: `"php": "^7.4 | ^8.0 | ^8.1",` While`^7.4` is  out of the equation since the package that you've added `"illuminate/collections": "^9.0",` needs ATLEAST PHP8.0! 😉 So it it was a Rector upgrade your Rector settings aren't correct since it should have updated the composer.json atleast in this case.

**Comment by aidan-casey** [comment]
Rector was not used to update this package. We will be sure to remove `7.4` from the composer file.
