### ISSUE TITLE
Has anybody setup webhooks for Autotask?

### ISSUE THREAD

**Issue by optmsp** [Anteris-Dev/autotask-client#79]
I don't think there is anything wrong with this library, but I am befuddle by the implementation of Autotask webhooks. Any help is appreciated.

So I see how you are required to subscribe PER FIELD for an entity. But the docs, and this lib, require (int) fieldID. But, Ticket.title for example does not have an (int) fieldID. How do you subscribe to changes in fields such as title, description, etc?

Anybody have examples?

**Comment by Darrrren** [comment]
This would be a great topic for the Discord group as I've been wondering about this myself!
Here's the link: https://discord.com/channels/750030802619727882/751452048071065690
