### ISSUE TITLE
Add "toString()" method to QueryBuilder

### ISSUE THREAD

**Issue by aidan-casey** [Anteris-Dev/autotask-client#9]
A "toString()" method on the Query Builder would be nice so you could see the raw request.

**Comment by Darrrren** [comment]
+1 to that @aidan-casey . Just found your project, following closely, nice job.

**Comment by aidan-casey** [comment]
Thanks for the feedback @Darrrren, I hope you find this package useful in any projects you may pursue!

I am going to add this to the roadmap for v0.3.0 and it should be implemented soon.

**Comment by Darrrren** [comment]
Sounds good, yep count me in, I'm happy to help where I can, I'll clone the project later in the week and take a good look around. I found your comment in the SOAP API repository, thanks for taking the time to post it.

**Comment by aidan-casey** [comment]
Awesome! Hope to continue to hear from you as you poke around.

**Comment by aidan-casey** [comment]
Closed by #17.
